name: bkrsnik
favicon: null
layout_spectrum: 0.7965716181788594
typography_spectrum: 0.27701525087468326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7644316316582263
  lightness: 0.6354919164441526
  saturation: 0.4719216029625386
  rhythmicContrast: 0.6245776668656617
purpose: []
